server:
  port: 8092
spring:
  application:
    name: gestionBancaire
  datasource:
    url: jdbc:mysql://localhost:3306/bank_db
    username: root
    password: kitalraph
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  default-produces-media-type: application/json

